### ISSUE TITLE
Can You Try Updating @actions/core in package.json

### ISSUE THREAD

**Issue by agadzinski93** [pinkasey/cpanel-deploy-action#4]
Greetings,
Found this action by chance and it's been great to see my .cpanel.yml file work!
Minor issue: Github Actions reports a warning of "The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

According to a blog - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ - simply updating @actions/core in your package.json to v1.10.0 or greater will use an updated version of the setOuput function in your index.js

That's all.

**Comment by pinkasey** [comment]
Thanks for the feedback!

Yes, of course - I'll update it and release a new version.

**Comment by pinkasey** [comment]
I've created a new version - `v1.1.2`.
Can you try it out and let me know it works well?
(Since it's a very trivial change, which I already did in [cpanel-repository-action](https://github.com/pinkasey/cpanel-repository-action) - I didn't test it this time).

Once you verify it, I'll mark it as "production ready" and "lasted release".

**Comment by agadzinski93** [comment]
Tested and no warnings! Thanks for the update!

**Comment by agadzinski93** [comment]
Closing issue.

**Comment by pinkasey** [comment]
Thanks @agadzinski93 
That was a nice collaboration.
